[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all]>=0.116.1",
    "kombu>=5.5.4",
    "redis>=6.4.0",
    "requests>=2.32.4",
]
